version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Run unit tests
          command: make test
      - run: make build
      - store_artifacts:
          destination: vault-plugin-secrets-cognito-linux-amd64
          path: vault/plugins/vault-plugin-secrets-cognito-linux-amd64
      - run: OS=darwin make build
      - store_artifacts:
          destination: vault-plugin-secrets-cognito-darwin-amd64
          path: vault/plugins/vault-plugin-secrets-cognito-darwin-amd64
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
